# Generated by Django 2.2.16 on 2020-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0002_auto_20201028_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/src/profile_pics'),
        ),
    ]
