# Generated by Django 2.2.16 on 2020-11-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0004_auto_20201117_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
