# Generated by Django 2.2.16 on 2020-12-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0007_auto_20201204_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='AnswerImages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
