# Generated by Django 2.2.16 on 2020-12-05 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quorumapi', '0008_auto_20201204_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
