# Generated by Django 2.2.16 on 2020-12-05 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0009_question_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='question',
            name='favourite',
            field=models.ManyToManyField(blank=True, max_length=5, related_name='favourite_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
