# Generated by Django 2.2.16 on 2020-12-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0011_questionvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote_score',
        ),
    ]
