# Generated by Django 2.2.16 on 2020-12-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0012_auto_20201206_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionvote',
            old_name='voted_by',
            new_name='user',
        ),
    ]
