# Generated by Django 2.2.16 on 2020-12-06 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quorumapi', '0013_auto_20201206_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='vote_score',
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlike', to='quorumapi.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answervote', to='quorumapi.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answervote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
