# Generated by Django 2.2.16 on 2020-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0014_auto_20201206_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
