# Generated by Django 2.2.16 on 2020-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorumapi', '0015_auto_20201214_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='favourite',
        ),
        migrations.AddField(
            model_name='question',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
