export const GET_USER = 'GET_USER'
export const LOGIN = 'LOGIN'
export const USER_LOADING = 'USER_LOADING'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const CLOSEALERT = "CLOSEALERT"
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

// export const GETALL_QUESTION_REQUEST = 'GETALL_QUESTION_REQUEST'
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
// export const GETALL_QUESTION_FAILURE = 'GETALL_QUESTION_FAILURE'

export const GET_QUESTION = 'GET_QUESTION'
export const QUESTION_LOADING = 'QUESTION_LOADING'
export const GET_QUESTION_ERROR = 'GET_QUESTION_ERROR'